### ISSUE TITLE
Ambiguous naming

### ISSUE THREAD

**Issue by Tako-San** [TheRedHotHabanero/ILab_2#2]
https://github.com/TheRedHotHabanero/ILab_2/blob/5326f6fada2b53764fb0a3334923a3efed5d07a7/1_cache/cache.h#L105-L117

Your `value` is key in fact. It even has type `KeyT`. I think that `key` is more appropriate name

**Comment by TheRedHotHabanero** [comment]
fixed in commit bd374150458f29e13106234e656babe28f3f4d15
