### ISSUE TITLE
Functions names

### ISSUE THREAD

**Issue by Tako-San** [TheRedHotHabanero/ILab_2#7]
https://github.com/TheRedHotHabanero/ILab_2/blob/c2fb220c0595b6ba80035a3da0bfd1a7e51b001e/1_cache/cache.h#L46

https://github.com/TheRedHotHabanero/ILab_2/blob/c2fb220c0595b6ba80035a3da0bfd1a7e51b001e/1_cache/cache.h#L53

https://github.com/TheRedHotHabanero/ILab_2/blob/c2fb220c0595b6ba80035a3da0bfd1a7e51b001e/1_cache/cache.h#L62

https://github.com/TheRedHotHabanero/ILab_2/blob/c2fb220c0595b6ba80035a3da0bfd1a7e51b001e/1_cache/cache.h#L70

https://github.com/TheRedHotHabanero/ILab_2/blob/c2fb220c0595b6ba80035a3da0bfd1a7e51b001e/1_cache/cache.h#L79

I think that it is better to name functions in present simple instead of present continuous.

**Comment by TheRedHotHabanero** [comment]
english mf do you speak it
